package com.smartbus.operations.controller;
import com.smartbus.operations.dto.EmergencyAttendanceReportRequest; import com.smartbus.operations.entity.*; import com.smartbus.operations.repository.EmergencyAttendanceReportRepository;
import jakarta.validation.Valid; import java.time.Instant; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api") public class EmergencyAttendanceReportController {
 private final EmergencyAttendanceReportRepository reports; public EmergencyAttendanceReportController(EmergencyAttendanceReportRepository reports){this.reports=reports;}
 @PostMapping("/incharge/emergency-reports") public ResponseEntity<EmergencyAttendanceReport> sendToTransport(@Valid @RequestBody EmergencyAttendanceReportRequest request){ EmergencyAttendanceReport report=new EmergencyAttendanceReport(); report.id=UUID.randomUUID(); report.busNumber=request.busNumber();report.busName=request.busName();report.inchargeName=request.inchargeName();report.reason=request.reason();report.location=request.location();report.status="SENT_TO_TRANSPORT";report.sentToTransportAt=Instant.now(); for(var item:request.students()){EmergencyReportStudent student=new EmergencyReportStudent();student.id=UUID.randomUUID();student.report=report;student.rollNumber=item.rollNumber();student.studentName=item.studentName();student.department=item.department();student.scannedAt=Instant.now();report.students.add(student);} return ResponseEntity.status(HttpStatus.CREATED).body(reports.save(report)); }
 @GetMapping("/admin/emergency-reports") public List<EmergencyAttendanceReport> transportReports(){return reports.findAllByOrderBySentToTransportAtDesc();}
 @PostMapping("/admin/emergency-reports/{id}/send-to-hod") public EmergencyAttendanceReport sendToHod(@PathVariable UUID id){EmergencyAttendanceReport report=reports.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Emergency attendance report not found"));if("SENT_TO_HOD".equals(report.status)) throw new ResponseStatusException(HttpStatus.CONFLICT,"Report was already sent to HOD");report.status="SENT_TO_HOD";report.sentToHodAt=Instant.now();return reports.save(report);}
 @GetMapping("/hod/emergency-reports") public List<EmergencyAttendanceReport> hodReports(){return reports.findByStatusOrderBySentToHodAtDesc("SENT_TO_HOD");}
 @PostMapping("/hod/emergency-reports/{id}/approve-attendance") public EmergencyAttendanceReport approveAttendance(@PathVariable UUID id){EmergencyAttendanceReport report=findForHod(id);report.attendanceApprovedAt=Instant.now();return reports.save(report);}
 @PostMapping("/hod/emergency-reports/{id}/give-permission") public EmergencyAttendanceReport givePermission(@PathVariable UUID id){EmergencyAttendanceReport report=findForHod(id);report.permissionGrantedAt=Instant.now();return reports.save(report);}
 private EmergencyAttendanceReport findForHod(UUID id){EmergencyAttendanceReport report=reports.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Emergency attendance report not found"));if(!"SENT_TO_HOD".equals(report.status))throw new ResponseStatusException(HttpStatus.CONFLICT,"Report has not been sent to HOD");return report;}
}
