import 'package:flutter/material.dart';
import '../theme/app_theme.dart';
import 'common_widgets.dart';

class ModernPrimaryButton extends StatelessWidget { const ModernPrimaryButton({super.key,required this.label,required this.icon,required this.onPressed, this.danger=false}); final String label; final IconData icon; final VoidCallback onPressed; final bool danger; @override Widget build(BuildContext context)=>SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:onPressed,icon:Icon(icon),label:Text(label),style:FilledButton.styleFrom(backgroundColor:danger?AppColors.danger:AppColors.primary,foregroundColor:Colors.white,padding:const EdgeInsets.symmetric(vertical:17),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(17))))); }
class PermissionTile extends StatelessWidget { const PermissionTile({super.key,required this.icon,required this.title,required this.detail, this.recommended=false}); final IconData icon; final String title,detail; final bool recommended; @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.symmetric(vertical:9),child:Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:AppColors.primary.withValues(alpha:.1),borderRadius:BorderRadius.circular(12)),child:Icon(icon,color:AppColors.primary)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),Text(detail,style:const TextStyle(color:AppColors.muted,fontSize:12))])),if(recommended)const Icon(Icons.check_circle_rounded,color:AppColors.success)])); }
class LiveStatusCard extends StatelessWidget { const LiveStatusCard({super.key}); @override Widget build(BuildContext context)=>SurfaceCard(color:const Color(0xFF0F172A),child:Row(children:[Container(height:12,width:12,decoration:const BoxDecoration(color:Color(0xFF22C55E),shape:BoxShape.circle,boxShadow:[BoxShadow(color:Color(0xAA22C55E),blurRadius:10)])),const SizedBox(width:10),const Expanded(child:Text('LIVE LOCATION SHARING',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800,letterSpacing:1.1))),const Icon(Icons.wifi_tethering_rounded,color:Colors.white)])); }
class SharingStatusCard extends StatelessWidget { const SharingStatusCard({super.key,required this.icon,required this.label,required this.value,required this.color}); final IconData icon; final String label,value; final Color color; @override Widget build(BuildContext context)=>SurfaceCard(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:color),const SizedBox(height:12),Text(label.toUpperCase(),style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700,color:AppColors.muted)),const SizedBox(height:4),Text(value,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w800))])); }
class TripInfoCard extends StatelessWidget { const TripInfoCard({super.key,required this.busNumber,required this.route,required this.driver}); final String busNumber,route,driver; @override Widget build(BuildContext context)=>SurfaceCard(child:Row(children:[Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:AppColors.primary.withValues(alpha:.1),borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.directions_bus_rounded,color:AppColors.primary,size:28)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(busNumber,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w800)),Text(route,style:const TextStyle(color:AppColors.muted,fontSize:12)),const SizedBox(height:3),Text('Driver: $driver',style:const TextStyle(fontSize:12,fontWeight:FontWeight.w600))]))])); }
class SessionTimerCard extends StatelessWidget { const SessionTimerCard({super.key,required this.time}); final String time; @override Widget build(BuildContext context)=>SurfaceCard(color:const Color(0xFFEFF6FF),child:Row(children:[const Icon(Icons.timer_outlined,color:AppColors.primary),const SizedBox(width:11),const Expanded(child:Text('Current session time',style:TextStyle(fontWeight:FontWeight.w700))),Text(time,style:const TextStyle(fontWeight:FontWeight.w800,color:AppColors.primary,fontSize:17))])); }
class ModernQRScannerOverlay extends StatefulWidget { const ModernQRScannerOverlay({super.key}); @override State<ModernQRScannerOverlay> createState()=>_ModernQRScannerOverlayState(); }
class _ModernQRScannerOverlayState extends State<ModernQRScannerOverlay> with SingleTickerProviderStateMixin { late final AnimationController c=AnimationController(vsync:this,duration:const Duration(seconds:2))..repeat(reverse:true); @override void dispose(){c.dispose();super.dispose();} @override Widget build(BuildContext context)=>Container(height:330,decoration:BoxDecoration(color:const Color(0xFF0F172A),borderRadius:BorderRadius.circular(28)),child:Stack(alignment:Alignment.center,children:[Container(width:220,height:220,decoration:BoxDecoration(border:Border.all(color:Colors.white,width:2),borderRadius:BorderRadius.circular(24))),AnimatedBuilder(animation:c,builder:(_,__)=>Positioned(top:65+c.value*190,left:70,right:70,child:Container(height:2,color:AppColors.primary))),const Icon(Icons.qr_code_scanner_rounded,size:94,color:Colors.white),const Positioned(bottom:24,child:Text('Ready to scan secure bus QR',style:TextStyle(color:Colors.white70))) ])); }
